Repository freezingsaddles/freezing-web, pull requests merged in 2024-11, with the labels that each got.

#215 Bring beloved leaderboards back
  freezing/web/templates/base.html
  freezing/web/templates/pointless/daily_variance.html
  leaderboards/adulting.yml
  leaderboards/hashtag.yml
  leaderboards/opmdays.yml
  leaderboards/parkfinder.yml
Labels: enhancement, help wanted

#276 Modernize loading of Google Charts
  freezing/web/static/js/html5shiv-3.7.0.js
  freezing/web/static/js/respond-1.3.0.min.js
  freezing/web/templates/base.html
  freezing/web/templates/explore/indiv_elev_dist.html
  freezing/web/templates/explore/riders_by_lowtemp.html
  freezing/web/templates/explore/team_cumul.html
  freezing/web/templates/explore/team_weekly_points.html
  freezing/web/templates/leaderboard/indiv.html
  freezing/web/templates/leaderboard/indiv_various.html
  freezing/web/templates/leaderboard/team.html
  freezing/web/templates/leaderboard/team_various.html
  freezing/web/templates/user/rides.html
Labels: enhancement, refactor

#288 Make the footer less ill-aligned
  freezing/web/static/css/styles.css
  freezing/web/templates/base.html
Labels: enhancement

#289 2025 season site reset docs improvement
  README.md
  freezing/sql/generate-table-counts-query.sql
  freezing/sql/table-counts-before-table-drop.sql
  freezing/sql/table-counts.sql
  freezing/sql/year-start.sql
Labels: enhancement, infrastructure
