Repository freezingsaddles/freezing-web, pull requests merged in 2024-12, with the labels that each got.

#308 Fix code scanning alert no. 2: DOM text reinterpreted as HTML
  freezing/web/templates/authorize.html
Labels: bug, refactor

#315 Fix Flask startup error from lack of instance_path
  .gitignore
  data/instance/.gitkeep
  freezing/web/__init__.py
  freezing/web/config.py
Labels: bug

#306 Restyle front-page stats
  freezing/web/static/css/styles.css
  freezing/web/static/js/ekko-lightbox-min.js
  freezing/web/templates/index.html
  freezing/web/templates/photos.html
  freezing/web/views/general.py
Labels: enhancement

#290 Add bandit security scanner
  .github/workflows/lint.yml
  .github/workflows/security.yml
  docker-compose.yml
  example.cfg
  freezing/web/config.py
  freezing/web/runserver.py
  freezing/web/utils/genericboard.py
  freezing/web/utils/insta.py
  freezing/web/views/alt_scoring.py
  freezing/web/views/chartdata.py
  requirements-test.txt
Labels: enhancement, python

#331 fix logging and geojson
  freezing/web/config.py
  freezing/web/views/api.py
  requirements.txt
Labels: bug, refactor

#333 Update some 2025 pointless prizes
  freezing/web/static/js/ride-map.js
  freezing/web/templates/base.html
  freezing/web/templates/pointless/generic.html
  freezing/web/utils/genericboard.py
  freezing/web/views/api.py
  freezing/web/views/pointless.py
  leaderboards/hashtag.yml
  leaderboards/parkfinder.yml
  leaderboards/poggio-indiv.yml
Labels: enhancement

#332 Authorization bypass with Impersonate button ONLY for localdev
  freezing/web/templates/base.html
  freezing/web/templates/people/show.html
  freezing/web/templates/pointless/foodrescue.html
  freezing/web/templates/pointless/generic.html
  freezing/web/templates/pointless/hashtag.html
  freezing/web/templates/pointless/rosshillloop.html
  freezing/web/templates/user/rides.html
  freezing/web/views/general.py
  freezing/web/views/people.py
  freezing/web/views/user.py
  leaderboards/hashtag.yml
  leaderboards/poggio-team.yml
Labels: enhancement, help wanted

#342 Add singlespeed to sponsored
  freezing/web/templates/base.html
  leaderboards/hashtag.yml
Labels: enhancement

#316 Fix freezing-web docker-compose setup
  .gitignore
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  README.md
  bin/fmt.sh
  bin/lint.sh
  data/mysql/sql/.gitkeep
  docker-compose.yml
  example.cfg
  freezing/web/__init__.py
  freezing/web/_faulthandler.py
  freezing/web/config.py
  freezing/web/runserver.py
  requirements-test.txt
  requirements.txt
  resources/docker/db/sql-scripts/.gitkeep
  resources/docker/settings.example.cfg
  resources/passenger/favicon.ico
  resources/passenger/passenger_wsgi.py
Labels: bug, infrastructure
