Repository freezingsaddles/freezing-web, pull requests merged in 2025-01, with the labels that each got.

#366 Fix hour vs hours on home page
  freezing/web/templates/index.html
  pyproject.toml
Labels: bug

#393 Hashtag #CABI counts as 2" real supple ride also
  leaderboards/suppleride.yml
Labels: enhancement

#395 Use pyproject for flake8 config
  .flake8
  .github/workflows/lint.yml
  freezing/web/templates/explore/distance_by_lowtemp.html
  leaderboards/hashtag.yml
  pyproject.toml
Labels: bug

#398 Rank by miles for #cabi leaderboard
  leaderboards/hashtag.yml
Labels: bug

#397 Eliminate requirements.txt in docs
  README.md
Labels: bug

#406 Add FawltyDeps linter
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Dockerfile
  docker-compose.yml
  freezing/web/static/css/leaflet-gesture-handling.min.css
  pyproject.toml
Labels: enhancement, dependencies, python

#407 gzip and cache track maps
  data/cache/json/.gitkeep
  docker-compose.yml
  example.cfg
  freezing/web/config.py
  freezing/web/views/api.py
Labels: enhancement

#410 Add daily ride total to person page
  freezing/web/templates/people/show.html
  freezing/web/views/people.py
Labels: enhancement

#418 Knock out three more google charts
  freezing/web/templates/explore/team_weekly_points.html
  freezing/web/templates/user/rides.html
  freezing/web/views/chartdata.py
  freezing/web/views/general.py
Labels: enhancement

#420 C3 cumulative charts and highlight self
  freezing/web/static/css/styles.css
  freezing/web/templates/explore/team_cumul.html
  freezing/web/templates/leaderboard/indiv_text.html
  freezing/web/templates/leaderboard/team_text.html
  freezing/web/views/chartdata.py
  freezing/web/views/leaderboard.py
Labels: enhancement

#421 Remove all usage of google charts
  freezing/web/static/css/styles.css
  freezing/web/templates/base.html
  freezing/web/templates/explore/distance_by_lowtemp.html
  freezing/web/templates/explore/indiv_elev_dist.html
  freezing/web/templates/explore/riders_by_lowtemp.html
  freezing/web/templates/explore/team_cumul.html
  freezing/web/templates/explore/team_weekly_points.html
  freezing/web/templates/leaderboard/indiv.html
  freezing/web/templates/leaderboard/indiv_various.html
  freezing/web/templates/leaderboard/team.html
  freezing/web/templates/leaderboard/team_various.html
  freezing/web/templates/user/rides.html
  freezing/web/utils/gviz_api.py
  freezing/web/views/chartdata.py
  freezing/web/views/general.py
  pyproject.toml
Labels: enhancement, refactor, dependencies

#422 Show team name in bubble tooltips
  freezing/web/templates/explore/indiv_elev_dist.html
  freezing/web/templates/leaderboard/team_various.html
  freezing/web/views/chartdata.py
Labels: enhancement

#426 Add wind chill, snowiness and raininess to riders/distance vs weather
  freezing/web/templates/base.html
  freezing/web/templates/explore/distance_by_lowtemp.html
  freezing/web/templates/explore/riders_by_lowtemp.html
  freezing/web/views/chartdata.py
Labels: enhancement

#427 fix wind chill
  freezing/web/views/chartdata.py
Labels: bug

#431 Add freeze points with friends
  freezing/web/static/css/styles.css
  freezing/web/templates/alt_scoring/indiv_freeze.html
  freezing/web/templates/alt_scoring/indiv_hains.html
  freezing/web/templates/alt_scoring/indiv_sleaze.html
  freezing/web/templates/alt_scoring/team_hains.html
  freezing/web/templates/alt_scoring/team_sleaze.html
  freezing/web/templates/base.html
  freezing/web/templates/index.html
  freezing/web/templates/leaderboard/indiv_various.html
  freezing/web/templates/leaderboard/team_various.html
  freezing/web/templates/tribes/leaderboard.html
  freezing/web/templates/tribes/my.html
  freezing/web/views/alt_scoring.py
  freezing/web/views/leaderboard.py
  freezing/web/views/shared_sql.py
Labels: enhancement

#432 fix with friends
  freezing/web/views/leaderboard.py
  freezing/web/views/shared_sql.py
Labels: bug

#433 Let the browser cache static files for 24 hours
  freezing/web/config.py
Labels: enhancement

#436 Styling consistency is key
  freezing/web/templates/alt_scoring/indiv_hains.html
  freezing/web/templates/alt_scoring/indiv_worst_day_points.html
  freezing/web/templates/alt_scoring/team_daily.html
  freezing/web/templates/alt_scoring/team_riders.html
  freezing/web/templates/leaderboard/indiv.html
  freezing/web/templates/leaderboard/indiv_text.html
  freezing/web/templates/leaderboard/team.html
  freezing/web/templates/leaderboard/team_text.html
  freezing/web/templates/people/show.html
  freezing/web/templates/pointless/coffeeride.html
  freezing/web/templates/pointless/distance.html
  freezing/web/templates/pointless/foodrescue.html
  freezing/web/templates/pointless/generic.html
  freezing/web/templates/pointless/kidsathlon.html
  freezing/web/templates/pointless/pointlesskids.html
  freezing/web/templates/pointless/points_per_mile.html
  freezing/web/templates/pointless/rosshillloop.html
  freezing/web/templates/pointless/segment.html
  freezing/web/views/shared_sql.py
Labels: enhancement

#444 Show team tooltips on ride maps
  freezing/web/static/js/ride-map.js
  freezing/web/views/api.py
Labels: enhancement
