Repository freezingsaddles/freezing-web, pull requests merged in 2025-02, with the labels that each got.

#441 Bump fawltydeps action version to latest
  .github/workflows/lint.yml
Labels: enhancement, dependencies

#443 Default to including private rides
  freezing/web/templates/authorize.html
Labels: enhancement

#442 Move responsibility for transaction commit up closer to where it belongs
  freezing/web/config.py
  freezing/web/data.py
  freezing/web/utils/auth.py
  freezing/web/views/general.py
Labels: bug

#447 Add your stats box to home page
  freezing/web/static/css/styles.css
  freezing/web/templates/index.html
  freezing/web/views/general.py
  leaderboards/pointlesskids.yml
Labels: enhancement

#452 Underline link
  freezing/web/templates/index.html
Labels: enhancement

#455 timezone horror pt 1
  freezing/web/views/general.py
Labels: bug

#456 timezone horror pt 2
  freezing/web/views/general.py
Labels: bug

#457 Sort photos by global time
  freezing/web/views/general.py
  freezing/web/views/photos.py
Labels: bug

#453 More sqlalchemy deprecations
  freezing/web/data.py
  freezing/web/views/chartdata.py
Labels: dependencies

#458 bump model to 0.11.3
  pyproject.toml
Labels: dependencies

#461 Clarify documentation on SQL session
  README.md
Labels: enhancement

#462 Fix friend links
  freezing/web/views/people.py
Labels: bug
